### PR TITLE
https://jira.desk.technology/browse/APIC-140

### PR DESCRIPTION
**Pull request by eldark88**
@nartiles please review

### CODE REVIEW

**Comment by nartiles** [comment]
What about the second item in the description?
- Should add a hook to DSAPIClient to change cache policy.

@eldark88 first pass done

**Comment by eldark88** [comment]
I changed cache policy in initializer of DSAPIClient like this:

```
        NSURLSessionConfiguration *config = [NSURLSessionConfiguration defaultSessionConfiguration];
        config.requestCachePolicy = NSURLRequestReturnCacheDataElseLoad;
        _session = [NSURLSession sessionWithConfiguration:config delegate:self delegateQueue:nil];
```

When I tested traffic through proxy, I didn't notice any change, and then I started diving more deeper to identify why it's not changing. After that I found that  we are also setting cache policy per request, which is overriding the cache policy for session. 

In DSAPIHTTPRequestSerializer line 296:

```
    NSMutableURLRequest *mutableRequest = [[NSMutableURLRequest alloc] initWithURL:url];
    mutableRequest.HTTPMethod = method;
    mutableRequest.allowsCellularAccess = self.allowsCellularAccess;
    mutableRequest.cachePolicy = self.cachePolicy;
    mutableRequest.HTTPShouldHandleCookies = self.HTTPShouldHandleCookies;
    mutableRequest.HTTPShouldUsePipelining = self.HTTPShouldUsePipelining;
    mutableRequest.networkServiceType = self.networkServiceType;
    mutableRequest.timeoutInterval = self.timeoutInterval;
```

Since cachePolicy in serializer is taking precedence, I think we can set cache policy like

```
let client = DSAPIClient()
client.requestSerializer.cachePolicy = .ReturnCacheDataElseLoad
```

@nartiles What do you think?

**Comment by nartiles** [comment]
Yea, makes sense

**Comment by eldark88** [comment]
@nartiles please review

**Comment by eldark88** [comment]
@nartiles This method clears the cache which is saved in filesystem. When the new instance of NSURLSession is created, it uses the cache which is generated by another NSURLSession(which no longer exist).

**Comment by eldark88** [comment]
@nartiles please review

**Comment by nartiles** [comment]
@eldark88 :shipit:

**Pull request merged**
