### PR TITLE
https://jira.desk.technology/browse/APIC-155

### PR DESCRIPTION
**Pull request by eldark88**
@nartiles please review

### CODE REVIEW

**Comment by eldark88** [comment]
@nartiles After pushing these changes I started looking into documentation more and I found out that Cases API (http://dev.desk.com/API/cases/#history) has also "class":"history", hence there will be a conflict when we make a request for Case history, it will return DSAPIOpportunityTimeline class.
I'm thinking about following workarounds:
1. Ask API team to change class name for something different. 
2. Use single class DSAPIHistory for both Case and Opportunity history. I notice that both Case and Opportunity history response have similar structure.

Thoughts?

**Comment by eldark88** [comment]
Btw, In https://github.com/forcedotcom/DeskApiClient-ObjC/pull/26 there was a similar scenario with attachments and I decided to use DSAPIAttachment class for both case and opportunity attachments.

**Comment by nartiles** [comment]
Regarding 'history', I think I'd prefer we have different classes similar to what we have for filters. Semantically, I don't see a reason why a case history would be the same as an opportunity history so even though they are similar now they could change later. However, before we ask the API team though I'd like to know what Android is doing and get on the same page with them. (BTW, they're out this week at Google IO).

Regarding 'attachments', I'm ok with attachment being the same class. This is more representative of a file so semantically I think its ok if they are the same.

**Comment by eldark88** [comment]
The resource classes doesn't have any model structure related logic. Hence, If the structure of the history API changes, it will not cause any issues. 
However, if in either of these API, we'll have case or opportunity specific methods (like: showOpportunityForHistory), in that case we might need to create a specific resource class.
Similar scenario we had with filters, where each filter API has specific methods for models it has relation. What if we take the same approach here? 
Start with DSAPIHistory class and if we have a new method specific to the model it is relating, than we create DSAPICaseHistory and DSAPIOpportunityHistory.
Btw, fyi, we don't have a DSAPIHistory class for cases. We are using DSAPIResource. 

I'm also very concerned about dynamic mapping resource classes based on "class" attribute. It is very brittle. 
If "class" attribute is changed on API side, it will cause a big issue on our end. I think we should eventually get rid of this approach.

**Comment by nartiles** [comment]
I'm ok with that. Start with one class and change later if we need to.

**Comment by eldark88** [comment]
@nartiles please review

**Comment by nartiles** [comment]
@eldark88 :shipit:

**Pull request closed without merging**
